### ISSUE TITLE
README setup gives me an error message

### ISSUE THREAD

**Issue by turbedi** [po-devs/po-web#101]
I get this error message when I try to run 'grunt less'
http://puu.sh/mrY2t.png
I don't get any error messages in the commands before.

**Comment by sulcata** [comment]
I happened to get this exact issue. I guess the file location changed or something. It should be fixed.

**Comment by Fuzzysqurl** [comment]
(16:40:39) +sulcata: https://github.com/po-devs/po-web/issues/101
(16:40:41) +sulcata: this one is fixed

**Comment by turbedi** [comment]
I get the same error message again after trying to run the command `grunt less` https://puu.sh/tAMId.png

**Comment by coyotte508** [comment]
@turbedi 

```bash
bower install
npm install

grunt copy
grunt concat
grunt less
```

You probably missed the `grunt copy` after `bower install`

**Comment by turbedi** [comment]
I still get the same error message :x

**Comment by coyotte508** [comment]
Ok @turbedi  was my bad, in https://github.com/po-devs/po-web/commit/bf00719804738594954d83fa8d4dd662bbaa32f0

Now after a `git pull` and `grunt copy`, it should be okay. (`app/assets/stylesheets/colorpicker.less` file should appear after `grunt copy`)

**Comment by turbedi** [comment]
Yep, works fine now. Thanks :3
