### ISSUE TITLE
Show type icon when hover a pokémon in battle

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#110]
<img src="http://www.serebii.net/pokedex-bw/type/normal.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/fire.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/water.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/electric.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/grass.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/ice.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/fighting.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/poison.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/ground.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/flying.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/psychic.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/bug.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/rock.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/ghost.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/dragon.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/dark.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/steel.gif"/> <img src="http://www.serebii.net/pokedex-bw/type/fairy.gif"/>

**Comment by danimesq** [comment]
Why is the reason to close it without any replies?

**Comment by coyotte508** [comment]
The type is already shown on hover, in text.

There is no screenshots, and it those icons seem like they would look out of place in the current on-hover pop-up. 

Please make a proper issue with full consideration and description.

**Comment by danimesq** [comment]
The ideia is show image of type instead of only text in the popunder of pokémon.
