### ISSUE TITLE
Animations and Images

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#111]
- [ ] Leech Seed
- [ ] Spikes
- [ ] Toxic Spikes
- [ ] Stealth Rock

**Comment by danimesq** [comment]
Thanks for merge all.

**Comment by coyotte508** [comment]
This is an animated battle window issue. The issue should be created in the appropriate repository: https://github.com/po-devs/po-battle-window

**Comment by danimesq** [comment]
https://github.com/po-devs/po-battle-window/issues/8 Ok
