### ISSUE TITLE
Notification counter in favicon

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#115]

**Comment by HearkOld** [comment]
I can take a stab at this

**Comment by DaniellMesquita** [comment]
Stab?

**Comment by DaniellMesquita** [comment]
Stab?

**Comment by DaniellMesquita** [comment]
Let me do it.

**Comment by DaniellMesquita** [comment]
Let me do it.

**Comment by coyotte508** [comment]
Imo a badge over the favicon. Either something like discord (with 0 for any thing, 1 / 2 / 3 / etc for things specific to the user) or just something that shows an alternate favicon when there's a pm / etc.

http://lab.ejci.net/favico.js/ seems like a good bet
