### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#116]

**Comment by Fuzzysqurl** [comment]
We already have these...?
![???](http://i.imgur.com/8G8aB3d.png)

**Comment by danimesq** [comment]
I use Google Chrome and don't seem to work.

**Comment by Fuzzysqurl** [comment]
Did you allow notifications from the website?

**Comment by danimesq** [comment]
Did PO has prompt the permission dialog? Not.
Not working.

**Comment by danimesq** [comment]
But heres a idea: I'm on Incognito mode, and not tested yet in a regular window. I'll try it now in Vivaldi browser, which is Chromium based.
