### ISSUE TITLE
Use this repo in Server and automatically push commits from remote

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#121]
I know that this isn't directly related to po-web, but have relation.
@coyotte508, will be nice if you use po-web's repo in your server and automatically push commits from remote, for all changes in reppo be automatically added to http://web.pokemon-online.eu/.

**Comment by DaniellMesquita** [comment]
@SteveC688, please see it.

**Comment by danimesq** [comment]
We've discussed about it in Slack.

**@skypo**:

> So like, unlike previous updates it would not require a server reset or a webapp reset to see the changes?
> as in manual reset

**@MaribelHearn**:

> it wouldn't require a reset indeed

Thanks for propusing it. I don't know if server reset is needed or not, but I think that need restart.
If need restart, I have a suggestion: reset the server one once by day.
