### ISSUE TITLE
Ferroseed Problem.

### ISSUE THREAD

**Issue by SkyPO** [po-devs/po-web#123]
In webclient, this particular Ferroseed set seems to cause some sort of problem when it comes to battling.

Ferroseed (M) @ Eviolite
Trait: Iron Barbs
EVs: 252 HP / 4 Def / 252 SDef
IVs: 0 Spd
Sassy Nature (+SDef, -Spd)
- Gyro Ball
- Leech Seed
- Spikes
- Protect

The one who uses ferroseed can play normally, however it's opponent, if team preview is on, once they chose their lead pokemon and the battle starts, they can't pick a move, cancel, switch, nothing.
As seen here. http://prntscr.com/b002nv

Retested using another eviolite pokemon, Aurist was using Gurdurr and everything ran normally.

**Comment by aurist** [comment]
[http://prntscr.com/b002k2](url)

perspective on battle from windows client side, battle appeared to be functioning normally but sky could not do anything after selecting a lead

**Comment by danimesq** [comment]
Thanks @aurist to report it and @SkyPO for see it in WebApp and report it.
It was the most curious bug I've seen. A joke: "in this bug PO is Brasilia, and Ferroseed is Dilma".
Is curious what only Ferroseed is being persecuted. I think that the problem is with a condition or more probable: a combination of factors. Such as a elemental type + a held item, etc. Please try Ferroseed's factors with other pokémons.

**Comment by danimesq** [comment]
@aurist your issue have relations with Ferroseed? Please fill an issue regarding it in https://github.com/po-devs/pokemon-online.

**Comment by sulcata** [comment]
Fuzzy looked into it and it seems like an issue with ferroseed having a short/non-existent animation.

**Comment by danimesq** [comment]
@Sulcata this is only with Ferroseed?

**Comment by Fuzzysqurl** [comment]
Yes

**Comment by danimesq** [comment]
[PkParaiso](http://www.pkparaiso.com/) can help.

**Comment by Fuzzysqurl** [comment]
Read sulcata'a last comment. The bug isn't in the Sprite itself, it's in the code that handles the animation... Or in Ferroseeds case, the lack thereof

**Comment by Fuzzysqurl** [comment]
https://github.com/po-devs/po-battle-window/issues/7

**Comment by turbedi** [comment]
Fixed by [this commit](https://github.com/po-devs/po-battle-window/commit/caae53b417448bdfe97671927ec58f37e9bd3cf8)

**Comment by MidwayMarshall** [comment]
wow turbedi I was trying to figure out how to reference that commit but now my life has no purpose

**Comment by turbedi** [comment]
uhh.. sorry? .-.

**Comment by coyotte508** [comment]
he's sad because he didn't know that just pasting a github commit link would reference to it in a pretty way.

**Comment by turbedi** [comment]
Who wants to take advantage of his mighty power and close this already fixed issue? :3

**Comment by coyotte508** [comment]
As soon as I update the webclient with the changes.

**Comment by turbedi** [comment]
This issue can be closed right?
