### ISSUE TITLE
Activate "Rainbow Mode" by default

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#125]

**Comment by danimesq** [comment]
My mom is calling me as "desocupated" an suggesting me to eat my notebook, brush my teeths and wash the dishes. "Since you like so much to work with, since you are working so hard there, go wash the dishes" I don't want it, and I'm very ocupated making PO better. Freemasonry will not prevent me to work.
I know GitHub isn't place for it, but here is the register. Sorry for me getting something off my chest.

**Comment by jinorae** [comment]
yo just do your dishes dude its for the greater good

**Comment by StrudelsPO** [comment]
r u ok

**Comment by sulcata** [comment]
i already did that in my commits a few hours ago

along with making idle not on by default, and making sort by auth on by default

**Comment by danimesq** [comment]
This will be usefull to pair the WebApp with the Desktop Program. Thank you, @Sulcata.
