### ISSUE TITLE
HTML server intro

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#128]
Like the Desktop client does:
<img src="http://i.imgur.com/iQXyfCQ.png"/>

**Comment by sulcata** [comment]
The problem is that there doesn't seem to be a good place to put it.

**Comment by danimesq** [comment]
We can use a top-left floating button to toggle it, or show in chat as block (not absolute like in desktop).

**Comment by danimesq** [comment]
@coyotte508, any comments?
