### ISSUE TITLE
Showing my user avatar and HTML info in other user popunders

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#141]
Me:

> All users here are appearing with default avatar 1 and without player info. Is it a new bug
> ?

@Skypo:

> Have you checked mine? as far as I know I have a customized avatar on my Zoroark alt
> and HTML info

<img src="http://i.imgur.com/IlswJD8.png">

Its comprovated, the po:user is only showing default avatar and not showing HTML info. Thanks @Skypo for help.

**Update**: What it shows is not the default avatar and blank HTML info, but my own avatar/Trainer Info. Thanks @IceKirby for the tip.

**Comment by sulcata** [comment]
I've been trying to fix that over the past few days, I think I know what caused it and why it's happening. Hint: if you step through the code slowly this won't happen!

**Comment by IceKirby** [comment]
I probably broke it when fixing Challenge Window not showing user/opponent's rating.
BTW, what it shows is not exactly the default avatar, but your own avatar/Trainer Info.

**Comment by coyotte508** [comment]
Ok can someone tell me who changed what where?

**Comment by DaniellMesquita** [comment]
@IceKirby It's not my avatar.

Skypo:
> Have you checked mine? as far as I know I have a customized avatar on my Zoroark alt
> and HTML info

**Comment by turbedi** [comment]
[This](https://github.com/po-devs/po-web/commit/547c9d98d703c007bd7c0d25a4ce758b0e119beb) and [this ](https://github.com/po-devs/po-web/commit/609c4e5cad85fafcc318ee1702a860555eacb6b4) commit changed code of the Chllenge Window

**Comment by IceKirby** [comment]
[This block](https://github.com/po-devs/po-web/commit/609c4e5cad85fafcc318ee1702a860555eacb6b4#diff-07c3cf0e94433e2b0b11f0dbb4570c2bR103) did it. It requests own ratings from server, but since it uses the same 'info' object it ends applying your own avatar/TI too.

**Comment by coyotte508** [comment]
Well ratings should already be gotten from "rankings" (network.js - line 350)

**Comment by IceKirby** [comment]
Oh I may have overcomplicated this. I remember not being able to get the 'ratings' property from other players without requesting it from the server, so I thought that was the same for ownPlayer.

An issue that I found with using the 'ratings' object for ownPlayer is that if your rating change (e.g.: after a you finish a rated battle) your new rating won't be updated on the Challenge Window (except if you check your own info).

**Comment by sulcata** [comment]
It is getting the info, the problem is when the code starts running asynchronously. If you step through it line by line in the debugger it actually works fine.

Oh, just realized this was closed, oops.
