### ISSUE TITLE
Port characteristics/features from Android app

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#143]
- [ ] #149 Server list in start page
- [ ] #150 Multilangual support
  - [ ] English packaged language
  - [ ] Portuguese language
  - [ ] French language
  - [ ] Spanish language
  - [ ] Deutch language
- [ ] Mobile Carroussel avatar list
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] Settings
  - [ ] Flashing
  - [ ] Flash Color
  - [ ] Flash Pop up
  - [ ] PM Time Stamp
  - [ ] Notifications
  - [ ] Cry Sound notification
  - [ ] Pokémon's cry
  - [ ] Volume
  - [ ] Save crash log
  - [ ] Copy and Paste

**Comment by IceKirby** [comment]
What would 'Save crash log' be in the webclient?

**Comment by coyotte508** [comment]
The list is messed up. There are notifications, there is flashing and so on.

After a working prototype of the application is made, we can see what's missing and _needed_ and create those (or this issue) then.
