### ISSUE TITLE
Notification HTML badges and short count in favicon

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#148]
The notification system can be increased.
- [x] Notification badge counting lines in pm tab
- [x] Notification badge counting mentions in channel tab
- [x] Notification badge counting mentions and other notifications in battle tab

`If 10 PM messages, 2 mentions and 30 battle tab notifications, all this can be shortened in favicon:`

If `10 messages` but **5 is from User** A and other **5 is from User B**, this is **counted as 2** in favicon (only counting user messages, not lines).

If `4 mentions`, but **2 is from Channel A** and other **2 is from Channel B**, this is **counted as 2** in favicon. (only count for each channel)

If `30 notifications` in **only one battle tab**, **count as 1**. Increase regarding number of channels in which this event repeats.

**Comment by coyotte508** [comment]
Why create another issue? There's already issue #115

**Comment by danimesq** [comment]
This is not a duplicate. The other issue is for counter/badge in favicon, this is another for improve counter and add badge to HTML elements.

**Comment by danimesq** [comment]
@coyotte508 please reopen it.

**Comment by coyotte508** [comment]
It's already like that.

That's why I said that creating an issue for something that doesn't exist is not a good idea.
