### ISSUE TITLE
Server list in start page

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#149]
Like the Android and Desktop client, my proposal is to move server list page from registry to WebClient and make it as start page, instead of automatically go to official server like PS does.

This is my draft on PowerPoint:

<img src="http://i.imgur.com/AtGQFDX.png">

**Comment by coyotte508** [comment]
No. It can be done for android etc but not webclient.

**Comment by danimesq** [comment]
But the plans is distribute WebClient for "android etc"....
Then, this can be used stealthy, which don't works only if is in web.pokemon-online.eu.

**Comment by coyotte508** [comment]
This issue will be reopened once there's an alpha version of any kind with the webclient distributed to desktop or android.

**Comment by danimesq** [comment]
@coyotte508 Its a problem. In this alpha version the user will can't connect to any server unless I use a iFrame/webview, what is not nice.
