### ISSUE TITLE
Use pokeballs to show status of players

### ISSUE THREAD

**Issue by coyotte508** [po-devs/po-web#16]
Currently players are in bold if they are auth, and blue if they are battling.

This doesn't look too pretty, so it'd be good to use correct css in `player-list.less` to show instead corresponding status pokeballs, which can be put in `public/images/playerstatus/` or w/e. It can be done [like that](http://stackoverflow.com/questions/735394/add-image-to-left-of-text-via-css)?

Then remove the bold / color stuff on player names.

**Comment by SteveC688** [comment]
Done!
