### ISSUE TITLE
New Accept/Decline buttons in challenge window

### ISSUE THREAD

**Issue by danimesq** [po-devs/po-web#161]
Bigger, colorized, repositioned and intuitive buttons:
<img src="http://i.imgur.com/U0WvPw0.png"/>

**Comment by coyotte508** [comment]
What's wrong with the current buttons?

**Comment by danimesq** [comment]
Are not intuitive.
I'm inspirated by the call screen of a smartphone, and I think its beautifull than the actual.

**Comment by coyotte508** [comment]
I'm not sure how spaced buttons like this are for the user's side.

If he hesitates between declining and accepting he will have to move his mouse a lot.

**Comment by danimesq** [comment]
It dependes on mouse position. Actually, the buttons are on right side. If user's mouse is in bottom-left, will have same effect. Important buttons like Accept/Decline need be separated. Do you think in user accidentally clicks on the wrong button?

**Comment by coyotte508** [comment]
I don't think on any modern UI a choice between only two things is separated by 400 pixels.

In github, in this page, "Comment" and "Close" are next to each other - although comment is in green. Maybe the same thing can be done here - "Accept" in green, and decline like it is.

**Comment by danimesq** [comment]
I don't believe on an avant modern UI with a Decline button near to a Accept button, but ok, I'll do it.

**Comment by danimesq** [comment]
Done. See the updated screenshot.

**Comment by coyotte508** [comment]
In addtion, red buttons are not used in web often except for important decisions.
