### ISSUE TITLE
Simple Battle Window improvements

### ISSUE THREAD

**Issue by coyotte508** [po-devs/po-web#170]
- [x] Show tooltip when hovering over poke
- [x] Show status next to name
- [x] Show gender next to name
- [x] Play music
- [x] Play cries
- [x] Handle substitute
- [x] Animated HP bars
- [x] Weathers

**Comment by Fuzzysqurl** [comment]
Re: Play Music
http://pastebin.com/fxunxz9H
Here's your loop positions

**Comment by Fuzzysqurl** [comment]
Also, will the battle window have a little mega icon like they do in game when they mega evolve?
![](http://pokejungle.net/wp-content/uploads/2014/07/Pokemon-ORAS-June-12-screenshot-18.jpg)

**Comment by coyotte508** [comment]
It's pretty obvious no? 

It can be added (and I would accept the PR!) but not a priority. Also, whoever does it has to be wary of the space issue. I uncentered the name already and put it to the left, there's gender and status icons, with the item icon in addition you have to be sure it fits all.
