### ISSUE TITLE
Smogon sets duplicated

### ISSUE THREAD

**Issue by Fuzzysqurl** [po-devs/po-web#172]
1. Select any pokemon with Smogon sets
2. Click the drop down
3. Count how many sets there are
   ![](http://i.imgur.com/MGgWhAI.png)
4. Select any set
5. Click the drop down again
6. The number of sets are halved, since they were initially duplicated.
   ![](http://i.imgur.com/tasGeS9.png)

**Comment by coyotte508** [comment]
Not for me...

Can you start from step 1? (empty team)

Edit: ok it happens on new team when selecting a fresh poke.

**Comment by Fuzzysqurl** [comment]
I guess there are additional steps, my bad
1. Log in
2. Create a non-full team (dunno if full team matters)
3. Click Update and close teambuilder
4. Close webclient
5. Start up webclient again and go to team builder
6. Select an empty slot in the team
7. Do the above steps
