### ISSUE TITLE
Nature Descriptions in Teambuilder

### ISSUE THREAD

**Issue by Weavile72** [po-devs/po-web#87]
I'd like to see what a nature does in brackets next to it in the scroll down list.
Hardy (Neutral)
Lonely (+Atk -Def)
Brave (+Atk -Spe)
Adamant (+Atk -SpA)
Naughty (+Atk -SpD)
Bold (+Def -Atk)
Docile (Neutral)
Relaxed (+Def -Spe)
Impish (+Def -SpA)
Lax (+Def -SpD)
Timid (+Spe -Atk)
Hasty (+Spe -Def)
Serious (Neutral)
Jolly (+Spe -SpA)
Naive (+Spe -SpD)
Modest (+SpA -Atk)
Mild (+SpA -Def)
Quiet (+SpA -Spe)
Bashful (Neutral)
Rash (+SpA -SpD)
Calm (+SpD -Atk)
Gentle (+SpD -Def)
Sassy (+SpD -Spe)
Careful (+SpD -SpA)
Quirky (Neutral)

Pretty sure those are all correct if that makes it any less work.

**Comment by coyotte508** [comment]
you can already select nature easily by clicking the stats. I tried adding those in the dropdown but it doesn't look great.

Maybe add the fact that you can click / right click stats in the description panel as a tip when nature is selected?
